CpuMonitor
    But : Calculer le taux d'utilisation du processeur (CPU) et lire sa fréquence à partir de /proc/stat et /proc/cpuinfo.
    update() : met à jour les données du processeur.
    getCpuUsage() : retourne le pourcentage d'utilisation du CPU.
    getCpuFreq() : retourne la fréquence actuelle du processeur.

MemoryMonitor
    But : Lire l'utilisation de la mémoire vive (RAM) et de la mémoire d'échange (Swap) depuis /proc/meminfo.
    update() : récupère les données mémoire.
    getUsedMemory(), getTotalMemory(), getUsedSwap(),...

ProcessMonitor
    But : Lister les processus actifs du système via le répertoire /proc/[pid].
    update() : récupère la liste des processus actifs.
    getProcessInfo() : affiche les processus sous forme de texte.
    getProcessRaw() : exporte les données au format CSV.

SysMon (interface principale)
    Combine les modules CPU, RAM et Processus, et fournit :
    update() : met à jour toutes les données.
    exportAsText() : affiche les données de façon lisible.
    exportAsCSV() : exporte les données au format CSV.
    run() : boucle de mise à jour/affichage à intervalle régulier.

main.cpp
    Met à jour les informations toutes les 2 secondes.
    Affiche les résultats avec SysMon::exportAsText().

test_CpuMonitor.cpp
    Appelle CpuMonitor::update() une première fois.
    Attend une seconde.
    Met à jour à nouveau et lit les résultats.
    Affiche l'utilisation CPU, la fréquence et les infos générales.

